name: Feature request
description: Suggest an improvement.
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested behavior and alternatives
